services:
  - type: web
    name: fixit-backend
    env: docker
    rootDir: apps/backend
    plan: free
    region: frankfurt
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PORT
        value: 3000
